'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''
latest = 0
last = 1
total = 0

print(latest)
print(last)

for i in range(0,50):
    temp_latest = latest
    latest = last
    last = temp_latest + last
    if last > 4000000:
        pass
    else:
        if last % 2 == 0:
            total += last
            print(last)

print("Total: " + str(total))

'''
Output:
0
1
2
8
34
144
610
2584
10946
46368
196418
832040
3524578
Total: 4613732
'''
